/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen.management.system;

import javax.swing.JOptionPane;
import model.User;
import dao.userdao;

/**
 *
 * @author user
 */
public class Forgotpassword extends javax.swing.JFrame {
    private String dbanswer =null;
    private String email=null;
    private String emailPattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    /**
     * Creates new form Forgotpassword
     */
    public Forgotpassword() {
        initComponents();
        btnupdate.setEnabled(false);
        btnsearch.setEnabled(false);
        txtsecurity.setEditable(false);
    }
    public void clear()
    {
      btnupdate.setEnabled(false);
      btnsearch.setEnabled(false);
      txtemail.setEditable(true);
      txtemail.setText("");
      txtsecurity.setText("");
      txtanswer.setText("");
    }
    public void validateEmail()
    {
     email=txtemail.getText();
     if(email.matches(emailPattern))
         btnsearch.setEnabled(true);
     else
         btnsearch.setEnabled(false);
    }
    public void validateFields()
    {
     String answer=txtanswer.getText();
     String password=txtnewpassword.getText();
     String security=txtsecurity.getText();
     if(!password.equals("")&&!answer.equals("")&&!security.equals(""))
         btnupdate.setEnabled(true);
     else
         btnupdate.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtanswer = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtsecurity = new javax.swing.JTextField();
        txtnewpassword = new javax.swing.JPasswordField();
        btnsearch = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        txtclear = new javax.swing.JButton();
        txtexit = new javax.swing.JButton();
        txtsignup = new javax.swing.JButton();
        txtlogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Forgot Password ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 215, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Security Question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 268, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Answer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 309, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("New Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 350, -1, -1));

        txtanswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtanswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtanswerKeyReleased(evt);
            }
        });
        getContentPane().add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 369, -1));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 212, 366, -1));

        txtsecurity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsecurity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsecurityKeyReleased(evt);
            }
        });
        getContentPane().add(txtsecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 265, 369, -1));

        txtnewpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnewpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnewpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtnewpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 369, -1));

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 211, -1, -1));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 405, -1, -1));

        txtclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        txtclear.setText("Clear");
        txtclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclearActionPerformed(evt);
            }
        });
        getContentPane().add(txtclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 405, -1, -1));

        txtexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        txtexit.setText("Exit");
        txtexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexitActionPerformed(evt);
            }
        });
        getContentPane().add(txtexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 405, -1, -1));

        txtsignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsignup.setText("Signup");
        txtsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsignupActionPerformed(evt);
            }
        });
        getContentPane().add(txtsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 471, -1, -1));

        txtlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtlogin.setText("Login");
        txtlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginActionPerformed(evt);
            }
        });
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 471, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Seamless-Canteen-Management-System-through-Biometric-Technology.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-22, -20, 1360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
     validateEmail();        
// TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtsecurityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecurityKeyReleased
    validateFields();        
// TODO add your handling code here:
    }//GEN-LAST:event_txtsecurityKeyReleased

    private void txtanswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanswerKeyReleased
        validateFields();// TODO add your handling code here:
    }//GEN-LAST:event_txtanswerKeyReleased

    private void txtnewpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewpasswordKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtnewpasswordKeyReleased

    private void txtexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexitActionPerformed
       int a =JOptionPane.showConfirmDialog(null,"do you really want to close application","select",JOptionPane.YES_NO_OPTION);
       if(a==0)
       {
           System.exit(0);
       }
// TODO add your handling code here:
    }//GEN-LAST:event_txtexitActionPerformed

    private void txtclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclearActionPerformed
  clear();        
// TODO add your handling code here:
    }//GEN-LAST:event_txtclearActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
      String answer=txtanswer.getText();
      String newpassword=txtnewpassword.getText();
      txtnewpassword.setText("");
      if(answer.equals(dbanswer))
      {
         userdao.update(email, newpassword);
         clear();
      }
      else
      {
         JOptionPane.showMessageDialog(null,"<html><b style=\"color:red\">Incorrect answer</b></html>","message",JOptionPane.ERROR_MESSAGE);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
    email=txtemail.getText();
      User user=null;
      user =userdao.getSecurityQuestion(email);
      if(user==null)
      {
          JOptionPane.showMessageDialog(null,"<html><b style=\"color:red\">Incorrect email</b></html>","message",JOptionPane.ERROR_MESSAGE);
      }
      else
      {
          btnsearch.setEnabled(false);
          txtemail.setEditable(false);
          dbanswer=user.getAnswer();
          txtsecurity.setText(user.getSecurityquestion());
          validateFields();
          
      }        
// TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsignupActionPerformed
      setVisible(false);
      new Signup().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsignupActionPerformed

    private void txtloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginActionPerformed
        setVisible(false);
      new Login().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JButton txtclear;
    private javax.swing.JTextField txtemail;
    private javax.swing.JButton txtexit;
    private javax.swing.JButton txtlogin;
    private javax.swing.JPasswordField txtnewpassword;
    private javax.swing.JTextField txtsecurity;
    private javax.swing.JButton txtsignup;
    // End of variables declaration//GEN-END:variables
}
