/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    public String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String useremail) {
        initComponents();
        email = useremail;
        if (!email.equals("admin@gmail.com")) {
            btncategory.setVisible(false);
            btnnewproduct.setVisible(false);
            btnviewdelete.setVisible(false);
            btnverify.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlogout = new javax.swing.JButton();
        btnplaceorder = new javax.swing.JButton();
        btnviewbill = new javax.swing.JButton();
        btnchangepass = new javax.swing.JButton();
        btnchangesecurity = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btncategory = new javax.swing.JButton();
        btnnewproduct = new javax.swing.JButton();
        btnviewdelete = new javax.swing.JButton();
        btnverify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        btnplaceorder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnplaceorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        btnplaceorder.setText("Place Order");
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });
        getContentPane().add(btnplaceorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 29, -1, -1));

        btnviewbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnviewbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        btnviewbill.setText("View Bill & Order Placed Details");
        btnviewbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewbillActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 29, -1, -1));

        btnchangepass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnchangepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Password.png"))); // NOI18N
        btnchangepass.setText("Change Password");
        btnchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangepassActionPerformed(evt);
            }
        });
        getContentPane().add(btnchangepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        btnchangesecurity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnchangesecurity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        btnchangesecurity.setText("Change Security Question");
        btnchangesecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangesecurityActionPerformed(evt);
            }
        });
        getContentPane().add(btnchangesecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 29, -1, -1));

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, -1, -1));

        btncategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        btncategory.setText("Manage Category ");
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        btnnewproduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnewproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        btnnewproduct.setText("New Product");
        btnnewproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        btnviewdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnviewdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        btnviewdelete.setText("View Edit & Delete Product");
        btnviewdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        btnverify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnverify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        btnverify.setText("Verify Users");
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1710, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed
        setVisible(false);
        new Placeorder(email).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnplaceorderActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "do you really want to close application?", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "do you really want to log out?", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        new Managecategory().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnnewproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewproductActionPerformed
        new Addnewproduct().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewproductActionPerformed

    private void btnviewdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdeleteActionPerformed
        new ViewandDeleteProduct().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewdeleteActionPerformed

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
       new Verifyusers().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnverifyActionPerformed

    private void btnviewbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewbillActionPerformed
        new ViewBills().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btnviewbillActionPerformed

    private void btnchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangepassActionPerformed
       new Changepassword(email).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchangepassActionPerformed

    private void btnchangesecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangesecurityActionPerformed
        new Securityquestion(email).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnchangesecurityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btnchangepass;
    private javax.swing.JButton btnchangesecurity;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnewproduct;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.JButton btnverify;
    private javax.swing.JButton btnviewbill;
    private javax.swing.JButton btnviewdelete;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
